### ISSUE TITLE
Creating conjure_error::Error from conjure generated error types

### ISSUE THREAD

**Issue by rahij** [palantir/conjure-rust#357]
## What happened?

Creating an internal or service error currently has the following signature:

```
pub fn service<E, T>(cause: E, error_type: T) -> Error
    where
        E: Into<Box<dyn error::Error + Sync + Send>>,
        T: ErrorType + Serialize,
    {
    }
```

Errors defined in conjure generate objects which only implement `ErrorType`.  Are users expected to create their own std::error::Error so that they can call this method?

**Comment by sfackler** [comment]
Yes, though many types implement `Into<Box<dyn Error>>`. For example, `&'static str` and `String` do, so you can do things like:

```rust
return Err(Error::service("you can't divide by 0", DivideByZeroError::new()));
```
